name: CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - "**/*.md"
  #     - "**/.gitignore"
  #     - "**/LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Verify pnpm Cache Path
        run: |
          if [ ! -d "$PNPM_HOME" ]; then
            echo "pnpm cache path does not exist: $PNPM_HOME"
            exit 1
          fi

      - name: Nightly Version
        working-directory: ./app
        run: |
          VERSION=$(jq -r '.version' package.json)
          SHORT_SHA=$(git rev-parse --short HEAD)
          DATE=$(date '+%Y%m%d')
          NEXT_VERSION=${VERSION}-${SHORT_SHA}-${DATE}
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
          echo "- \`VERSION\`: ${{env.NEXT_VERSION}}" >> $GITHUB_STEP_SUMMARY

  nightly:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Print List
        run: |
          find ./ -type f
