name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/.gitignore"
      - "**/LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: version
        working-directory: ./app
        run: |
          VERSION=$(jq -r '.version' package.json)
          SHORT_SHA=$(git rev-parse --short HEAD)

          DATE=$(date '+%Y%m%d')
          NEXT_VERSION=${VERSION}-${SHORT_SHA}-${DATE}
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV

      - name: Update version
        run: |
          echo "- \`VERSION\`: ${{env.NEXT_VERSION}}" >> $GITHUB_STEP_SUMMARY
